server:
  context-path: /ems
  jsp-servlet:
    init-parameters:
      development: true
  port: 7899
spring:
  profiles:
    include: product
  datasource:
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    password: admins
    url: jdbc:mysql://localhost:3306/ems
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  mapper-locations: classpath:/com/hsp/dao/impl/*.xml
  type-aliases-package: com.hsp.entity